site_name: RPI TNFS Server
site_url: https://example.com/
nav:
    - Home: index.md
    - Digital Ocean: digocean.md
    - Ubuntu Pi Image: ubuntu.md
    - Autossh: autossh.md
    - Wireguard: wireguard.md
    - ZFS: zfs.md
    - TNFS: tnfs.md
    - AP: ap.md
    
    